services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rupeelens
      POSTGRES_PASSWORD: rupeelens
      POSTGRES_DB: rupeelens
    volumes:
      - rupeelens_pg:/var/lib/postgresql/data

volumes:
  rupeelens_pg:
