import "./global.css";

import { AuthSessionWatcher } from "@/features/auth";

export const metadata = {
  description: "Generated by create-nx-workspace",
  title: "Welcome to rupeelens-fe",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen antialiased">
        <AuthSessionWatcher />
        {children}
      </body>
    </html>
  );
}
